version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27107/investai
      - POSTGRES_URI=postgresql://postgres:postgres@postgres:5432/investai
      - JWT_SECRET=super_secret_jwt_token_for_investai_aws_prod
      - CLIENT_URL=http://localhost:8080
      - LLM_PROVIDER=gemini
    depends_on:
      - mongodb
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=investai
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  postgres_data:
